_wandb:
    value:
        cli_version: 0.21.1
        e:
            nyaggucnca6rq264gn756i6f2fcoz5kw:
                email: hanseikai2019@gmail.com
                executable: /home/hanse/miniconda3/envs/rapids-23.12/bin/python
                git:
                    commit: 63c60cbebe503e9919babee10a1b642470cf2e8c
                    remote: git@github.com:pauljkerry/binary-bank.git
                host: Lucille
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: notebooks/tuning/03_gpu_tuning.ipynb
                python: CPython 3.10.18
                root: /home/hanse/kaggle/binary-bank/notebooks/tuning
                startedAt: "2025-09-25T07:22:05.532863Z"
                writerId: nyaggucnca6rq264gn756i6f2fcoz5kw
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 5
                - 6
                - 35
                - 53
                - 105
            "2":
                - 5
                - 6
                - 35
                - 53
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
colsample_bytree:
    value: 0.592797576724562
data_id:
    value: "033"
early_stopping_rounds:
    value: null
learning_rate:
    value: 0.02
max_depth:
    value: 8
min_child_weight:
    value: 95.07143064099162
n_fold:
    value: 10
reg_alpha:
    value: 0.0007482139197236472
reg_lambda:
    value: 0.000602521573620386
subsample:
    value: 0.7394633936788146
